version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=qwerty007
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5435:5432'
volumes:
  postgres: